# Generated by Django 4.2.17 on 2025-03-14 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def add_default_job_statuses(apps, schema_editor):
    JobStatus = apps.get_model('job', 'JobStatus')
    JobStatus.objects.bulk_create([
        JobStatus(name='pending', description='Job is pending'),
        JobStatus(name='in progress', description='Job is currently in progress'),
        JobStatus(name='complete', description='Job is complete'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.RunPython(add_default_job_statuses),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='JobTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='job.job', verbose_name='Job')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Technician')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.jobstatus', verbose_name='Status'),
        ),
    ]
