# Generated by Django 4.2.17 on 2025-03-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobstatus_job_description_jobtech_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
